---
title: "data1"
author: "Julia Du"
date: "`r lubridate::today()`"
output: html_document
---

## Load necessary libraries
```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(lubridate)
library(ggrepel)
library(broom)
library(googlesheets4)
library(janitor)
library(viridis)

library(waffle)
library(hrbrthemes)
library(extrafont)
library(ggthemes)

theme_set(theme_minimal())
```

## Import data
```{r}
test <- read_sheet("https://docs.google.com/spreadsheets/d/1EOzWrUxbi6h-fQwcdvLzLyAziyejw3cSYbZWp7WV_1M/edit#gid=113582572", sheet = 2)

# spreadsheet 1?
# how attendance changes over yrs & at diff locations

```

## Play around with data
```{r clean_data}
materials_df <- test %>%
  clean_names() %>%
 # select(15:19, -17) %>%
  rename(
    materials_often = what_materials_do_you_always_need_and_often_have_to_purchase,
    materials_when = what_materials_do_you_purchase_when_you_can,
    materials_dream = what_materials_do_you_dream_of_purchasing_but_cant_usually_afford_or_find,
    materials_donated = what_materials_if_any_do_you_get_donated) %>%
  mutate(materials_dream = sapply(materials_dream, toString),
         materials_donated = sapply(materials_donated, toString)) %>%
  mutate_all(.funs = tolower) 

materials_df %>%
  select(timestamp, materials_often) %>%
  mutate(mat1 = strsplit(materials_often, ",")) %>%
  unnest(mat1) %>%
  mutate(mat1 = str_trim(mat1)) %>% 
  group_by(mat1) %>%
  summarize(count = n()) %>%
  arrange(-count)


materials_freq <- function(mat_col, suffix){
  length_df <- materials_df %>%
    count() %>%
    pull()
  
  materials_df %>%
    select(timestamp, {{mat_col}}) %>%
    mutate(mat = strsplit({{mat_col}}, ",")) %>%
    unnest(mat) %>%
    mutate(mat = str_trim(mat)) %>%
    group_by(mat) %>%
    summarize(count = n()) %>%
    mutate(prop = count/length_df) %>%
    arrange(-count) %>%
    mutate(mat = as_factor(mat))
   # rename("mat_{suffix}" := mat)
  #  slice_head(n = 10)
}
```



```{r}
mat_piechart <- function(freq5_df){
  freq5_df %>%
    mutate(mat = fct_rev(mat),
           cumulative = cumsum(count),
           midpoint = cumulative - count/2, 
           label = scales::percent(prop)) %>%
    ggplot(aes(x = 1, weight = count, fill = mat)) +
    geom_bar(width = 1, position = "stack") +
    coord_polar(theta = "y") +
    geom_text(aes(x = 1.3, y = midpoint, label = label), color = "white") + 
    scale_fill_viridis(discrete = TRUE, option = "turbo") +
    guides(fill = guide_legend(title = "Materials")) +
    labs(subtitle = "As of Apr. 2021", x = "Materials", 
         y = "Number of teachers", fill = "", 
         caption = "Note: Top 5 materials only, so chart does not add up to 100%") +
    theme_void() +
    theme(legend.position = "bottom")
}

materials_freq(materials_often) %>%
  slice_head(n = 5) %>%
  mat_piechart() +
  labs(title = "Top 5 materials always needed & most frequently bought")

materials_freq(materials_when) %>%
  drop_na(mat) %>%
  slice_head(n = 5) %>%
  mat_piechart() +
  labs(title = "Top 5 materials bought when funds allow")

materials_freq(materials_dream) %>%
  slice_head(n = 5) %>%
  mat_piechart() +
  labs(title = "Top 5 materials desired but unable to afford or find")

materials_freq(materials_donated) %>%
  slice_head(n = 5) %>%
  mat_piechart() +
  labs(title = "Top 5 materials received through donations")

```


# other possible graphs - ask for maggie's opinion
```{r}
# https://cran.r-project.org/web/packages/extrafont/README.html
#font_import() - only needs to be done once
loadfonts(device = "win")


# column graph
materials_freq(materials_often) %>%
  slice_head(n = 10) %>%
  ggplot(mapping = aes(x = mat, y = count, fill = mat, label = count)) +
  geom_col() +
  labs(title = "Materials most often used and bought by teachers", 
       subtitle = "As of Apr. 2021", 
       x = "Materials", y = "Number of teachers", fill = "") +
  geom_label() +
  theme_ipsum() +
  theme(legend.position = "none")  


#waffle graph
#materials_freq(materials_often) %>%
 # slice_head(n = 5) %>%
  
wip %>%
  ggplot(aes(fill = mat, values = count)) +
  geom_waffle(n_rows = 20, size = 0.33, color = "white") +
  coord_equal() +
  theme_ipsum(grid = "") +
  theme_enhance_waffle() +
  ggthemes::scale_fill_tableau(name = NULL)
```


# helpful links

* **https://stackoverflow.com/questions/41338757/adding-percentage-labels-on-pie-chart-in-r**

* https://www.r-graph-gallery.com/piechart-ggplot2.html

# FUNCTIONING code for graphs (before wrote function)
```{r, eval = FALSE}
# column graph
materials_freq(materials_often) %>%
  slice_head(n = 10) %>%
  ggplot(mapping = aes(x = mat, y = count, fill = mat, label = count)) +
  geom_col() +
  labs(title = "Materials most often used and bought by teachers", 
       subtitle = "As of Apr. 2021", 
       x = "Materials", y = "Number of teachers", fill = "") +
  geom_label() +
  theme(legend.position = "none")

## this works!!! gives % labels
wip <- materials_freq(materials_often) %>%
  slice_head(n = 5) 
wip %>%
  mutate(
    mat = fct_rev(mat),
    cumulative = cumsum(count),
    midpoint = cumulative - count/2, 
    label = scales::percent(prop)) %>%
ggplot(aes(x = 1, weight = count, fill = mat)) +
  geom_bar(width = 1, position = "stack") +
  coord_polar(theta = "y") +
  geom_text(aes(x = 1.3, y = midpoint, label = label), color = "white") + 
  scale_fill_viridis(discrete = TRUE, option = "turbo") +
  guides(fill = guide_legend(title = "Materials")) +
  labs(title = "Top 5 materials most often used and bought by teachers", 
       subtitle = "As of Apr. 2021", 
       x = "Materials", y = "Number of teachers", fill = "") +
  theme_void()
```

```{r, eval = FALSE}
# helpful pie graph, but labels are misplaced
ggplot(aes(x = "", y = count, fill = mat)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  geom_label_repel(aes(label = scales::percent(prop)), size=2, show.legend = F, nudge_x = 3) +
  guides(fill = guide_legend(title = "Materials"))

# old pie graph - labels also misplaced
materials_freq(materials_often) %>%
  slice_head(n = 5) %>%
  mutate(ypos = cumsum(prop)- 0.5*prop ) %>%
  ggplot(aes(x="", y=prop, fill = mat, label = prop)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  theme_void() + 
  labs(title = "Materials most often used and bought by teachers", 
       subtitle = "As of Apr. 2021", 
       x = "Materials", y = "Number of teachers", fill = "") +
#  theme(legend.position="none") +
  geom_text(aes(y = ypos, label = mat), color = "white", size=5) #+
#  geom_label(aes(y = ypos*.3), size = 2)
```





# can ignore
material_count <- function(material_string){
  materials_df %>%
    filter(str_detect(material, material_string)) %>%
    count() %>%
    mutate(material = material_string)
}





```{r}
genre_count <- function(genre_string){
  manga_75 %>%
    filter(str_detect(genre, genre_string)) %>%
    count() %>%
    mutate(genre = genre_string)
}

genres_of_interest <- c("Action", "Comedy", "Drama", "Fantasy", "Romance")

# visualize manga overall
map_dfr(genres_of_interest, genre_count) %>%
  ggplot(mapping = aes(x = genre, y = n, fill = genre, label = n)) +
  geom_col() +
  labs(title = "Common genres in 75 top-ranked mangas", 
       subtitle = "As of Mar. 2021", 
       x = "Genre", y = "Number of mangas", fill = "", 
       caption = "Source: mangaupdates.com") +
  geom_label() +
  theme(legend.position = "none")
```


##



